<a href="https://colab.research.google.com/github/SnehithaNalluri/Python-mini-project-/blob/main/Introduction_to_Numpy_S2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Numpy - Numeric Python
#Most powerful package - Library

#Numpy- Dimensions

#A - One Dimensional Array
#[A,B] || [A
#.         B] - Two Dimensional Array - Row || Column

#Three Dimensional

#Array- Storing,Manipulating, Similar Data Type

#Faster than sny mathematical functions
#convinient compared to other packages.
#Memory Efficiency
#Support multi dimensional arrays

#speed(Numpy operations) >speed,(Lists operations)
#size(Numpy operations) < size(Lists operationns)
#Memory Optimization (Numpy) > Memory Optimisation (List operations)

In [ ]:
#Install numpy - pip3 install numpy // pip install numpy

In [ ]:
import numpy as np

In [ ]:
#Create a numpy array
# ID array

arrID = np.array([1,2,3,4,5])
print(arrID)

[1 2 3 4 5]


In [ ]:
#creating 2D array - Matrix
arr2D = np.array([
    [0,0,0],[0,0,0]

])



In [ ]:
print(arr2D)

[[0 0 0]
 [0 0 0]]


In [ ]:
#creating arrays with default values

#Creating matrix with all elements as '0


allZeroes = np.zeros([2,3])
print(allZeroes)

#Creating matrix with all values of elements as '1'
allOnes = np.ones([2,3])
print(allOnes)

#Creating matrix with all value of elements 'constant value - n - Fill value'

allConstant = np.full([2,3],6)
print(allConstant)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[6 6 6]
 [6 6 6]]


In [ ]:
#Create an identity matrix - I

Identity = np.eye(4)
print(Identity)

#Identity Matrix - Aij = 1 && Aij = 0
#For all A Belongs to R MxN
#Aij -



[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#Creating random Matrices

# between  0 and 1
rand1 = np.random.rand(3,3)
print(rand1)

#between a and b
rand2 = np.random.randint(10,20,(3,3))
print(rand2)

[[0.73954133 0.01638612 0.40175129]
 [0.61329975 0.01849879 0.71981861]
 [0.19280279 0.74813623 0.07201806]]
[[10 10 11]
 [13 14 16]
 [11 12 13]]


In [ ]:







#Array properties

arr = np.array([[1,2,3,4],[2,3,4,5]])
print(arr)

#Shape of array
print(f'\nThe shape of the array is {arr.shape}')

#Size of array
print(f'\nThe size of the array is {arr.size}')
#Datatype
print(f'\nThe Datatype of the array is {arr.dtype}')

#Dimensions of array
print(f'\nThe Dimensions of the array is {arr.ndim}')

[[1 2 3 4]
 [2 3 4 5]]

The shape of the array is (2, 4)

The size of the array is 8

The Datatype of the array is int64

The Dimensions of the array is 2


In [ ]:
#indexing and Slicing

#Access the elements in 1D Array
arr = np.array([1,2,3,4])
print(arr)
print(arr[3])

#Slicing the elements

print(arr[0:3])

# Access the element in 2D array
arr2 = np.array([[1,2,3],[2,3,4]])
print(arr2)

print(arr2[1,1])
print(arr2[0,:]) # first row with all columns
print(arr2[:,0]) # first column with all rows



[1 2 3 4]
4
[1 2 3]
[[1 2 3]
 [2 3 4]]
3
[1 2 3]
[1 2]


In [ ]:
#l1 = []
#[l1.append(_) for _ in range(10)]

l1 = np.arange(10,-10,-3)

print(l1)


[10  7  4  1 -2 -5 -8]


In [ ]:
#Mathematical operations

a = np.array([1,2,3])
b = np.array([3,4,5])

print(f'The sum of a and b is { a+b}')
print(f'The difference of a and b is {a-b}')
print(f'The product of a and b is {a*b}')
print(f'The division of a and b is {a/b}')

The sum of a and b is [4 6 8]
The difference of a and b is [-2 -2 -2]
The product of a and b is [ 3  8 15]
The division of a and b is [0.33333333 0.5        0.6       ]


In [ ]:
#Matrix Multiplication
b1 = np.array([[1,2,3],[2,3,4]])
b2 = np.array([[5,6],[7,8],[1,3]])

#Dot product --- product = AB ---A. m x n --- B n x p
c = np.dot(b1,b2)
print(c)

[[22 31]
 [35 48]]


In [ ]:
print(b1)

[[1 2 3]
 [2 3 4]]


In [ ]:
print(b2)

[[5 6]
 [7 8]
 [1 3]]


In [ ]:
#Statistical operations
mean = c.mean()
max = c.max()
median= np.median(c)
std = np.std(c)
var = np.var(c)

In [ ]:
print(mean)

34.0


In [ ]:
print(max)

48


In [ ]:
print(median)

33.0


In [ ]:
print(std)

9.354143466934854


In [ ]:
print(var)

87.5


In [ ]:
std*std

87.50000000000001

In [ ]:
#Trignometric functions

#Sin(x)
#Cos(x)
#Tan(x)
#Cosec - Sin(x)/Cos(x)
#Sec - 1/Cos(x)
#Cot - 1/Tan(x)

angles = np.array([0,15,30,45,60,75,90])

#Sin(array)

result = np.sin(np.radians(angles))
result1 = np.cos(np.radians(angles))
result2 = np.tan(np.radians(angles))



In [ ]:
print(result)
print(result1)
print(result2)

[0.         0.25881905 0.5        0.70710678 0.8660254  0.96592583
 1.        ]
[1.00000000e+00 9.65925826e-01 8.66025404e-01 7.07106781e-01
 5.00000000e-01 2.58819045e-01 6.12323400e-17]
[0.00000000e+00 2.67949192e-01 5.77350269e-01 1.00000000e+00
 1.73205081e+00 3.73205081e+00 1.63312394e+16]


In [ ]:
arr = np.array([1,2,3,4,5,6])

#Reshape the array
reshapedarr = arr.reshape(2,3)

print(reshapedarr)


[[1 2 3]
 [4 5 6]]


In [ ]:
#Convert / Flatten any n dim array
flattenedarr = arr.flatten()

print(flattenedarr)

[1 2 3 4 5 6]


In [ ]:
#Stacking the data






arr1 = np.array([1,2,3,4])
arr2 = np.array([10,20,30,40])

#Vertical Stacking
arr3 = np.vstack((arr1,arr2))

print(f'The shape of arr3 is { arr3.shape}')

#Horizontal stacking
arr4 = np.hstack((arr1,arr2))
print(f'The shape of arr4 is {arr4.shape}')
print(arr4)

The shape of arr3 is (2, 4)
The shape of arr4 is (8,)
[ 1  2  3  4 10 20 30 40]


In [ ]:
#Filtering
arr = np.array([10,20,30,40,50,60,70,80])

farr = arr[arr>40]

print(farr)

[50 60 70 80]
