<a href="https://colab.research.google.com/github/SnehithaNalluri/Python-mini-project-/blob/main/Introduction_to_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Numpy - Numeric Python
#Most powerful package - Library

#Numpy- Dimensions

#A - One Dimensional Array
#[A,B] || [A
#.         B] - Two Dimensional Array - Row || Column

#Three Dimensional

#Array- Storing,Manipulating, Similar Data Type

#Faster than sny mathematical functions
#convinient compared to other packages.
#Memory Efficiency
#Support multi dimensional arrays

#speed(Numpy operations) >speed,(Lists operations)
#size(Numpy operations) < size(Lists operationns)
#Memory Optimization (Numpy) > Memory Optimisation (List operations)

In [ ]:
#Install numpy - pip3 install numpy // pip install numpy

In [ ]:
import numpy as np

In [ ]:
#Create a numpy array
# ID array

arrID = np.array([1,2,3,4,5])
print(arrID)

[1 2 3 4 5]


In [8]:
#creating 2D array - Matrix
arr2D = np.array([
    [0,0,0],[0,0,0]

])



In [9]:
print(arr2D)

[[0 0 0]
 [0 0 0]]


In [20]:
#creating arrays with default values

#Creating matrix with all elements as '0


allZeroes = np.zeros([2,3])
print(allZeroes)

#Creating matrix with all values of elements as '1'
allOnes = np.ones([2,3])
print(allOnes)

#Creating matrix with all value of elements 'constant value - n - Fill value'

allConstant = np.full([2,3],6)
print(allConstant)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[6 6 6]
 [6 6 6]]


In [19]:
#Create an identity matrix - I

Identity = np.eye(4)
print(Identity)

#Identity Matrix - Aij = 1 && Aij = 0
#For all A Belongs to R MxN
#Aij -



[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [23]:
#Creating random Matrices

# between  0 and 1
rand1 = np.random.rand(3,3)
print(rand1)

#between a and b
rand2 = np.random.randint(10,20,(3,3))
print(rand2)

[[0.73954133 0.01638612 0.40175129]
 [0.61329975 0.01849879 0.71981861]
 [0.19280279 0.74813623 0.07201806]]
[[10 10 11]
 [13 14 16]
 [11 12 13]]


In [43]:







#Array properties

arr = np.array([[1,2,3,4],[2,3,4,5]])
print(arr)

#Shape of array
print(f'\nThe shape of the array is {arr.shape}')

#Size of array
print(f'\nThe size of the array is {arr.size}')
#Datatype
print(f'\nThe Datatype of the array is {arr.dtype}')

#Dimensions of array
print(f'\nThe Dimensions of the array is {arr.ndim}')

[[1 2 3 4]
 [2 3 4 5]]

The shape of the array is (2, 4)

The size of the array is 8

The Datatype of the array is int64

The Dimensions of the array is 2


In [44]:
#indexing and Slicing

#Access the elements in 1D Array
arr = np.array([1,2,3,4])
print(arr)
print(arr[3])

#Slicing the elements

print(arr[0:3])

# Access the element in 2D array
arr2 = np.array([[1,2,3],[2,3,4]])
print(arr2)

print(arr2[1,1])
print(arr2[0,:]) # first row with all columns
print(arr2[:,0]) # first column with all rows



[1 2 3 4]
4
[1 2 3]
[[1 2 3]
 [2 3 4]]
3
[1 2 3]
[1 2]


In [54]:
#l1 = []
#[l1.append(_) for _ in range(10)]

l1 = np.arange(10,-10,-3)

print(l1)


[10  7  4  1 -2 -5 -8]


In [58]:
#Mathematical operations

a = np.array([1,2,3])
b = np.array([3,4,5])

print(f'The sum of a and b is { a+b}')
print(f'The difference of a and b is {a-b}')
print(f'The product of a and b is {a*b}')
print(f'The division of a and b is {a/b}')

The sum of a and b is [4 6 8]
The difference of a and b is [-2 -2 -2]
The product of a and b is [ 3  8 15]
The division of a and b is [0.33333333 0.5        0.6       ]


In [61]:
#Matrix Multiplication
b1 = np.array([[1,2,3],[2,3,4]])
b2 = np.array([[5,6],[7,8],[1,3]])

#Dot product --- product = AB ---A. m x n --- B n x p
c = np.dot(b1,b2)
print(c)

[[22 31]
 [35 48]]


In [62]:
print(b1)

[[1 2 3]
 [2 3 4]]


In [63]:
print(b2)

[[5 6]
 [7 8]
 [1 3]]
